### ISSUE TITLE
Gaming API Developer Dashboard UI

### ISSUE THREAD

**Issue by RyRy79261** [ChainSafe/files-ui#1565]
Src: https://github.com/ChainSafe/game-pm/issues/34

#### Create a dashboard that allows developers to

- Sign in (social or web3)
- Create a profile (so we can learn more about their projects, goals, etc. and get in touch for user research and marketing)
- Create a "project" and generate an associated key/endpoint to include in their game so that they can use the API
- Manage projects (delete, edit, re-issue key/endpoint, etc.)
- See their current API usage by project and in total (# of calls per day/month)
- See their current tier and what usage that allows them (and have a button to upgrade their tier)
- Generate analytics we can use in the backend for user insights

#### Concurrent needs:

- Can API keys have Project ID added - Peter/Arun
- Can Kong be updated for each project - Ronny
- Where are usage limits retrieved/stored- Peter/Arun & Ronny
- Plans prices & features need to be confirmed - Alex/Leon/BD
- Products set up for billing - Peter/Arun

## Phase 0

- [x] web2 & web3 login
- [x] API key Creation & Deletion
- [ ] Snazzy front end dashboard
- [ ] API key generation wired up to game-api Kong rate limits - Dependent on Ronny: API creation on UI must update Kong DB

## Phase 1

- [ ] Usage metrics - Needs endpoint to fetch data - Peter & Arun/Ronni to be consulted on data source
- [ ] Profile creation

## Phase 2

- [ ] Introduction of Priced tiers - Dependent on BD
- [ ] Stripe based card Billing - Peter & Arun to be consulted; Creating products & updating Gaming usage via webhooks
- [ ] Multiple API keys for projects
  - [ ] Keys have project id field - Peter & Arun to be consulted: Is this straightforward to add to JWT
  - [ ] Kong can interpret project ID field - Ronny to confirm
  - [ ] Purchasing a plan updates Kong for all projects - Arun & Ronny

**Comment by Tbaut** [comment]
moved to https://github.com/ChainSafe/files-design/issues/121
