### ISSUE TITLE
Upgrade Plan Flow - Credit Card

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/files-ui#1757]
Overview of the flow being implemented is on [Figma](https://www.figma.com/file/wRMGqc11iQLVpDVmqXVXWK/ChainSafe-Files?node-id=2192%3A1309) - Designs are now mostly complete for this.

![image](https://user-images.githubusercontent.com/12774278/143598568-94b623eb-cd58-4b9c-ae6d-7816dcf44c21.png)

- Add a Subscription Overview modal to be displayed after the user has selected a new subscription. This should allow a user to choose annual or monthly billing
![image](https://user-images.githubusercontent.com/12774278/142232421-0a781c28-a162-4c9e-abea-b41e92cf1868.png)

- Add a payment method selection modal to allow a user to select a payment method for their subscription. 
  - ~~The crypto option should only be enabled if `Annual` subscription was selected previously.~~ For now just have the crypto option disabled
  - The card option should only be enabled if a card has been added
  - If a card has been added, display the card details
![image](https://user-images.githubusercontent.com/12774278/143602119-254522cd-dcdd-4f63-bc90-63e147af326c.png)
![image](https://user-images.githubusercontent.com/12774278/143602273-0e4fe6e9-ccfb-4c38-8f9a-9c4855e7ca06.png)

- If the user does not have a card added an expansion panel with the card details form should be displayed allowing the user to add a card.
  - Handle 3D Secure authentication while adding a card. When `Use this payment method` is clicked, display the 3DS iframe over the Payment Method modal:
![image](https://user-images.githubusercontent.com/12774278/143600208-415fb3f6-1a78-4ac9-b826-2f2dd151e1ea.png)

- Add a confirmation modal once successful payment has been processed
![image](https://user-images.githubusercontent.com/12774278/142234561-b287a2c4-d88d-44ca-89c5-5de263bf0432.png)

### Questions
- [x] How to integrate the crypto into the existing UX
  - Crypto will be handled in the next issue
- [x] Can we use the existing Add Card component in this modal
  - Yes
- [x] Does choosing to `Edit` an existing card just replace the default card on Stripe?
  - Currently no, and we should figure out where this functionality will be implemented (API or UI) as with the current UI it makes sense not to store any unnecessary

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1757?planning-poker) with ZenHub @tanmoyAtb @RyRy79261

**Comment by FSM1** [comment]
@tanmoyAtb I updated the description a bit, with screen grabs from the latest Figma. Please shout if anything is unclear.
