### ISSUE TITLE
Share reconstruction on login

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/files-ui#756]
This module should perform the following functionality:
- [x] Determine whether an account has a password share, and allow the user to recover their key with a password
- [x] Allow the user to recover their key with a backup phrase
- [x] Handle when users enter invalid password or backup phrase
- [x] Log out of the account (and ensure that the share transfer request is deleted (this should be handled in the threshold key context
- [x] Handle the Save New Device 

![image](https://user-images.githubusercontent.com/12774278/111404258-1eeef700-86d7-11eb-8e18-4d1e0e5a01b6.png)
https://www.figma.com/file/wRMGqc11iQLVpDVmqXVXWK/ChainSafe-Files---Dev?node-id=2974%3A0
