### ISSUE TITLE
Login Page - Initial Screen

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/files-ui#822]
The login page needs some polish.
- [ ] Ensure spinner is on the clicked OAuth button. There is no need for a spinner on the web3 button as this will take the user to the `Choose Wallet Provider` screen.
- [ ] Ensure all text elements are translated
- [ ] Wire up the web3 auth flow - See figma for details
- [ ] Wire up error handling screen and error messages

![image](https://user-images.githubusercontent.com/12774278/111401014-27443380-86d1-11eb-8660-a8d7c73a3297.png)

https://www.figma.com/file/wRMGqc11iQLVpDVmqXVXWK/ChainSafe-Files---Dev?node-id=2814%3A0
